### ISSUE TITLE
Rofi and Dmenu doesn't launch in i3.

### ISSUE THREAD

**Issue by Overfl0w-grrrl** [jbcallv/dotfiles#1]
Rofi and Demi doesn't work, even after modifications in the i3 config file.
Steps to reproduce the bug: 
1. Try to launch Rofi or Dmenu by using the pre-existing shortcut or a custom one.
2. Rofi or Dmenu should have launched, but they don't.

**Comment by jbcallv** [comment]
So the issue is that they just don't open? No error messages?

EDIT: oops accidentally clicked close issue :D

**Comment by Overfl0w-grrrl** [comment]
![IMG_20210224_182857](https://user-images.githubusercontent.com/69017917/109080227-2faadf00-76ce-11eb-81eb-6adcea9f514c.jpg)
![IMG_20210224_182850](https://user-images.githubusercontent.com/69017917/109080235-3174a280-76ce-11eb-9494-ad39ca558cd5.jpg)
![IMG_20210224_182839](https://user-images.githubusercontent.com/69017917/109080240-333e6600-76ce-11eb-9277-6c8840e5e2d8.jpg)

**Comment by jbcallv** [comment]
Comment out the resize lines and also comment out the split toggle lines. Then run and sent output again.

**Comment by Overfl0w-grrrl** [comment]
This is the i3 error file.

**Comment by jbcallv** [comment]
Yes, I know those pictures show the i3 error file. It looks like you have a duplicate keybinding or you are using i3-wm instead of i3-gaps-wm. Please comment out the lines (using '#' for comments) that are for resizing the gaps and also the split toggle lines. Then restart i3 (mod+shift+r) and see if the error persists. If so, please post a picture of the i3 error file output.

**Comment by Overfl0w-grrrl** [comment]
EDIT: The error fixed itself for some reason. (Idk how, but now it opens and it works)
